version: '3.1'
services: 

  # session-broker:
  #   image: session-broker
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     - APPLICATION_SECRET="op]jIFEyPr3o?;``Y<3xusa6EK/t:s<Lp@H]n=q^vg05ogW8^0Qi0NqF=mAnU?]f"
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./session-broker:/session-broker
  #   depends_on:
  #     - postgres
  #     - adminer
  #   restart: on-failure

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
     - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080